services:
    mysql-server:
        image: mysql:8.4.2
        platform: linux/x86_64 # thêm lệnh này để chạy được trên Mac M1, nếu lỗi trên chip Intel thì xóa ra
        ports:
            - 3399:3306 # nếu muốn đổi thì chỉ cần đổi số 3399, không được đổi 3306
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql # nếu để dòng này thì dòng bên dưới sẽ không có tác dụng
            - ./mysql/sql/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user

    web:
        build: ./www
        restart: always
        ports:
            - 8080:80 # for php application
        volumes:
            - ./www:/var/www/html/
            - ./www/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./www/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - "mysql-server"
        environment:
            Environment: Production
            mariadbPwd: root
            mariadbUser: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_HOST=mysql-server
        depends_on:
            - "mysql-server"
    wsserver:
        build: ./ws-server
        restart: always
        ports:
            - 8081:8080 # for collaboration web server
        volumes:
            - ./ws-server:/var/www/html/
        depends_on:
            - "mysql-server"
        environment:
            Environment: Production
            mariadbPwd: root
            mariadbUser: root
